# Generated by Django 2.1.2 on 2020-10-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajedrez_app', '0011_auto_20201012_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha_Inicio')),
                ('duracion', models.IntegerField()),
                ('ahora', models.DateTimeField()),
                ('aceptada', models.BooleanField()),
                ('cancelada', models.BooleanField()),
                ('jugador1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicita', to='ajedrez_app.Jugador')),
                ('jugador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responde', to='ajedrez_app.Jugador')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partida', to='ajedrez_app.Partida')),
            ],
        ),
    ]
