# Generated by Django 2.1.2 on 2019-11-17 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Federacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=25)),
                ('comunidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ganadas', models.IntegerField()),
                ('perdidas', models.IntegerField()),
                ('empatadas', models.IntegerField()),
                ('elo', models.IntegerField()),
                ('numfederado', models.IntegerField()),
                ('conectado', models.BooleanField()),
                ('anyosexperiencia', models.IntegerField()),
                ('federacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ajedrez_app.Federacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_movimiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_partida', models.IntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha_Inicio')),
                ('duracion', models.DateTimeField()),
                ('tiempo_establecido', models.DateTimeField()),
                ('chat_id', models.IntegerField()),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ajedrez_app.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pieza', models.CharField(max_length=15)),
                ('num_pieza', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='images/')),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('celda', models.CharField(max_length=5)),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ajedrez_app.Movimiento')),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ajedrez_app.Partida')),
            ],
        ),
    ]
