# Generated by Django 2.1.2 on 2020-10-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajedrez_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='federacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ajedrez_app.Federacion'),
        ),
    ]
