# Generated by Django 2.1.2 on 2020-10-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajedrez_app', '0003_auto_20201003_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conectados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jugador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ajedrez_app.Jugador')),
            ],
        ),
        migrations.AlterField(
            model_name='partida',
            name='jugador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ajedrez_app.Jugador'),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='partida',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ajedrez_app.Partida'),
        ),
    ]
