# Generated by Django 2.1.2 on 2020-10-10 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajedrez_app', '0004_auto_20201010_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('mensaje', models.CharField(max_length=255)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinatario', to='ajedrez_app.Jugador')),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emisor', to='ajedrez_app.Jugador')),
            ],
        ),
    ]
