# Generated by Django 2.1.2 on 2020-10-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajedrez_app', '0005_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conectado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jugador_conectado', to='ajedrez_app.Jugador')),
            ],
        ),
        migrations.RemoveField(
            model_name='conectados',
            name='jugador',
        ),
        migrations.DeleteModel(
            name='Conectados',
        ),
    ]
