# Generated by Django 2.1.2 on 2020-10-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajedrez_app', '0006_auto_20201010_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='estado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
