# Generated by Django 2.1.2 on 2020-10-11 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajedrez_app', '0008_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
